defaultTown:
economyEnabled: false
mayorsCanBuyTerritories: false
pricePerXZBlock: 0
minNumPlayersToBuyTerritory: 3
allowTownFriendlyFireManagement: false;
#default is wooden hoe (290)
quickSelectTool: WOOD_HOE
#log verbose information of each MCTowns command issued
logCommands: false
playersCanJoinMultipleTowns: true
#Maximum number of tiles in the XZ plane that a mayor can use when making a territory
# default is a generous 50 chunks (50 * 16 = 800)
territoryXZSizeLimit: 800
#
#
#The currently installed version of MCTowns. Do not change this.
installedVersion: ${version}
#Seriously don't change it
#
#
