name: MCTowns
main: cafe.josh.mctowns.MCTownsPlugin
version: ${version}-${buildNumber}
softdepend: [WorldGuard, Vault]
commands:
    mct:
        description: Base command for plugin-wide config or generic commands
        usage: /mct (addtown | removetown | info | join | list | refuse | cancel | donate)
        aliases:
    town:
        description: base command for all town-based commands
        usage: /town (add | remove | active | list | motd | setmayor | bank | spawn | economy | joinmethod | pvp)
        aliases: [to, mtown]
    territory:
        description: base command for all territory-based commands
        usage: /territory (add | redefine | remove | active | list | flag)
        aliases: [te, mterrit]
    plot:
        description: base command for all plot-based commands
        usage: /plot (add | redefine | remove | active | list | sign | info | flag | economy)
        aliases: [pl, mplot]
